//! Manifest-driven code generation for typed `orleans-rust-client` grain
//! clients.
//!
//! This is intentionally limited (see the repository roadmap). It consumes a
//! manifest emitted by the .NET bridge (`GetManifest` / `OrleansRustBridge.Tools`)
//! and produces one Rust struct per grain contract that wraps a
//! [`orleans_rust_client::GrainRef`] with typed methods.
//!
//! Type mapping covers the common primitive .NET types; anything unrecognised
//! falls back to `serde_json::Value`, keeping the generator robust against
//! manifests it does not fully understand.

use heck::{ToPascalCase, ToSnakeCase};
use serde::Deserialize;

/// Errors produced while generating client code.
#[derive(thiserror::Error, Debug)]
pub enum CodegenError {
    /// The manifest JSON could not be parsed.
    #[error("failed to parse manifest: {0}")]
    Parse(#[from] serde_json::Error),
    /// The manifest was structurally valid but unusable.
    #[error("invalid manifest: {0}")]
    Invalid(String),
}

/// A contract manifest, matching the JSON shape emitted by the bridge.
#[derive(Debug, Clone, Deserialize)]
pub struct Manifest {
    /// Orleans service id the bridge connects to.
    #[serde(default)]
    pub service_id: String,
    /// Orleans cluster id the bridge connects to.
    #[serde(default)]
    pub cluster_id: String,
    /// Bridge version that produced the manifest.
    #[serde(default)]
    pub bridge_version: String,
    /// Manifest schema version.
    #[serde(default)]
    pub schema_version: String,
    /// Grain contracts.
    #[serde(default)]
    pub grains: Vec<GrainContract>,
}

/// A single grain contract.
#[derive(Debug, Clone, Deserialize)]
pub struct GrainContract {
    /// Fully-qualified grain interface name.
    pub interface_name: String,
    /// Grain type alias used for dispatch.
    pub grain_type: String,
    /// Methods exposed by the grain.
    #[serde(default)]
    pub methods: Vec<GrainMethod>,
    /// Key kinds the grain supports (`string`, `int64`, `guid`).
    #[serde(default)]
    pub supported_key_kinds: Vec<String>,
}

/// A single grain method.
#[derive(Debug, Clone, Deserialize)]
pub struct GrainMethod {
    /// Method name as exposed on the grain interface.
    pub name: String,
    /// Request (single-argument) .NET type name, or empty for no argument.
    #[serde(default)]
    pub request_type: String,
    /// Response .NET type name, or empty for no return value.
    #[serde(default)]
    pub response_type: String,
    /// Payload codec; only `json` is supported by the generator.
    #[serde(default)]
    pub payload_codec: String,
}

impl Manifest {
    /// Parse a manifest from a JSON string.
    ///
    /// # Errors
    /// Returns [`CodegenError::Parse`] if the JSON is malformed.
    pub fn from_json_str(json: &str) -> Result<Self, CodegenError> {
        Ok(serde_json::from_str(json)?)
    }
}

/// Options controlling generation.
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    /// Crate path used to reference the runtime client.
    pub client_crate: String,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            client_crate: "orleans_rust_client".to_owned(),
        }
    }
}

/// Generate Rust source for every grain in `manifest`.
///
/// # Errors
/// Returns [`CodegenError::Invalid`] if a grain contract cannot be turned into
/// a valid Rust identifier.
pub fn generate(manifest: &Manifest, options: &CodegenOptions) -> Result<String, CodegenError> {
    let mut out = String::new();
    out.push_str("// @generated by orleans-rust-codegen. Do not edit by hand.\n");
    out.push_str("// Include within a module annotated `#[allow(dead_code, clippy::all)]`.\n\n");
    out.push_str(&format!(
        "use {client}::{{GrainKey, GrainRef, OrleansClient, OrleansError}};\n\n",
        client = options.client_crate
    ));

    for grain in &manifest.grains {
        out.push_str(&generate_grain(grain, options)?);
        out.push('\n');
    }

    Ok(out)
}

fn generate_grain(
    grain: &GrainContract,
    _options: &CodegenOptions,
) -> Result<String, CodegenError> {
    let struct_name = client_struct_name(&grain.interface_name)?;
    let key = KeyStrategy::from_kinds(&grain.supported_key_kinds);

    let mut s = String::new();
    s.push_str(&format!(
        "/// Typed client for `{}`.\n",
        grain.interface_name
    ));
    s.push_str(&format!(
        "pub struct {struct_name} {{\n    inner: GrainRef,\n}}\n\n"
    ));
    s.push_str(&format!("impl {struct_name} {{\n"));
    s.push_str(&format!(
        "    /// Construct a client bound to `key`.\n    pub fn new(client: OrleansClient, key: {key_param}) -> Self {{\n        Self {{\n            inner: client.grain(\n                \"{interface}\",\n                \"{grain_type}\",\n                {key_expr},\n            ),\n        }}\n    }}\n",
        key_param = key.param_type(),
        interface = grain.interface_name,
        grain_type = grain.grain_type,
        key_expr = key.key_expr(),
    ));

    for method in &grain.methods {
        s.push('\n');
        s.push_str(&generate_method(method));
    }

    s.push_str("}\n");
    Ok(s)
}

fn generate_method(method: &GrainMethod) -> String {
    let fn_name = sanitize_ident(&method.name.to_snake_case());
    let response_ty = map_type(&method.response_type);

    let request_ty = map_type(&method.request_type);
    let takes_arg = request_ty != "()";

    let (signature_arg, call_arg) = if takes_arg {
        (format!(", value: {request_ty}"), "&value".to_owned())
    } else {
        (String::new(), "&()".to_owned())
    };

    format!(
        "    /// Invokes `{orig}`.\n    pub async fn {fn_name}(&self{signature_arg}) -> Result<{response_ty}, OrleansError> {{\n        self.inner.invoke_json(\"{orig}\", {call_arg}).await\n    }}\n",
        orig = method.name,
    )
}

#[derive(Debug, Clone, Copy)]
enum KeyStrategy {
    String,
    Int64,
    Guid,
}

impl KeyStrategy {
    fn from_kinds(kinds: &[String]) -> Self {
        for kind in kinds {
            match kind.as_str() {
                "int64" => return KeyStrategy::Int64,
                "guid" => return KeyStrategy::Guid,
                _ => {}
            }
        }
        KeyStrategy::String
    }

    fn param_type(self) -> &'static str {
        match self {
            KeyStrategy::String => "impl Into<String>",
            KeyStrategy::Int64 => "i64",
            KeyStrategy::Guid => "uuid::Uuid",
        }
    }

    fn key_expr(self) -> &'static str {
        match self {
            KeyStrategy::String => "GrainKey::String(key.into())",
            KeyStrategy::Int64 => "GrainKey::Int64(key)",
            KeyStrategy::Guid => "GrainKey::Guid(key)",
        }
    }
}

fn client_struct_name(interface_name: &str) -> Result<String, CodegenError> {
    let last = interface_name.rsplit('.').next().unwrap_or(interface_name);
    let trimmed = last
        .strip_prefix('I')
        .filter(|rest| rest.chars().next().is_some_and(char::is_uppercase))
        .unwrap_or(last);
    let base = trimmed.to_pascal_case();
    if base.is_empty() {
        return Err(CodegenError::Invalid(format!(
            "cannot derive a client name from interface `{interface_name}`"
        )));
    }
    Ok(format!("{base}Client"))
}

/// Map a .NET type name to a Rust type. Unknown types fall back to
/// `serde_json::Value` so generation never fails on an unfamiliar type.
fn map_type(dotnet: &str) -> String {
    let normalized = dotnet.trim();
    match normalized {
        "" | "void" | "System.Void" | "System.Threading.Tasks.Task" => "()".to_owned(),
        "System.String" | "string" => "String".to_owned(),
        "System.Boolean" | "bool" => "bool".to_owned(),
        "System.SByte" | "sbyte" => "i8".to_owned(),
        "System.Byte" | "byte" => "u8".to_owned(),
        "System.Int16" | "short" => "i16".to_owned(),
        "System.UInt16" | "ushort" => "u16".to_owned(),
        "System.Int32" | "int" => "i32".to_owned(),
        "System.UInt32" | "uint" => "u32".to_owned(),
        "System.Int64" | "long" => "i64".to_owned(),
        "System.UInt64" | "ulong" => "u64".to_owned(),
        "System.Single" | "float" => "f32".to_owned(),
        "System.Double" | "double" => "f64".to_owned(),
        "System.Guid" => "uuid::Uuid".to_owned(),
        _ => "serde_json::Value".to_owned(),
    }
}

fn sanitize_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true",
        "type", "unsafe", "use", "where", "while",
    ];
    if RESERVED.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_owned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derives_client_name() {
        assert_eq!(
            client_struct_name("Counter.Abstractions.ICounterGrain").unwrap(),
            "CounterGrainClient"
        );
        assert_eq!(
            client_struct_name("ICounterGrain").unwrap(),
            "CounterGrainClient"
        );
    }

    #[test]
    fn maps_primitive_types() {
        assert_eq!(map_type("System.Int64"), "i64");
        assert_eq!(map_type(""), "()");
        assert_eq!(map_type("Some.Custom.Type"), "serde_json::Value");
    }

    #[test]
    fn generates_counter_client() {
        let manifest = Manifest {
            service_id: "s".into(),
            cluster_id: "c".into(),
            bridge_version: "0.1.0".into(),
            schema_version: "1".into(),
            grains: vec![GrainContract {
                interface_name: "Counter.Abstractions.ICounterGrain".into(),
                grain_type: "counter".into(),
                supported_key_kinds: vec!["string".into()],
                methods: vec![
                    GrainMethod {
                        name: "Get".into(),
                        request_type: String::new(),
                        response_type: "System.Int64".into(),
                        payload_codec: "json".into(),
                    },
                    GrainMethod {
                        name: "Add".into(),
                        request_type: "System.Int64".into(),
                        response_type: "System.Int64".into(),
                        payload_codec: "json".into(),
                    },
                ],
            }],
        };

        let code = generate(&manifest, &CodegenOptions::default()).unwrap();
        assert!(code.contains("pub struct CounterGrainClient"));
        assert!(code.contains("pub async fn get(&self) -> Result<i64, OrleansError>"));
        assert!(code.contains("pub async fn add(&self, value: i64) -> Result<i64, OrleansError>"));
    }
}
