using System.Text;

namespace OrleansRustBridge.Tools;

/// <summary>
/// Generates C# <c>IBridgeGrainInvoker</c> source for a discovered grain
/// (the brief's "Mode A" adapters). Experimental: covers methods with zero or
/// one parameter and Task/Task&lt;T&gt; returns, which fits the common case.
/// </summary>
public static class InvokerGenerator
{
    /// <summary>Generate a single invoker source file.</summary>
    public static string Generate(DiscoveredGrain grain, string @namespace)
    {
        var iface = CsType(grain.Interface);
        var className = ClassName(grain);
        var keyExpr = grain.KeyKind switch
        {
            "int64" => "invocation.Key.AsInt64()",
            "guid" => "invocation.Key.AsGuid()",
            _ => "invocation.Key.AsString()",
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated /> Produced by orleans-rust-bridge-tools. Do not edit.");
        sb.AppendLine("using Orleans;");
        sb.AppendLine("using OrleansRustBridge.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className} : IBridgeGrainInvoker");
        sb.AppendLine("{");
        sb.AppendLine($"    public string InterfaceName => \"{grain.InterfaceName}\";");
        sb.AppendLine($"    public string GrainType => \"{grain.GrainType}\";");
        sb.AppendLine($"    public global::System.Collections.Generic.IReadOnlyList<string> SupportedKeyKinds => new[] {{ \"{grain.KeyKind}\" }};");
        sb.AppendLine();
        sb.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<BridgeMethodDescriptor> Methods => new[]");
        sb.AppendLine("    {");
        foreach (var method in grain.Methods)
        {
            var request = GrainReflection.TypeName(method.RequestType);
            var response = GrainReflection.TypeName(method.ReturnType);
            sb.AppendLine($"        new BridgeMethodDescriptor(\"{method.Name}\", \"{request}\", \"{response}\"),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task<byte[]> InvokeAsync(");
        sb.AppendLine("        IClusterClient client,");
        sb.AppendLine("        BridgeInvocation invocation,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var grain = client.GetGrain<{iface}>({keyExpr});");
        sb.AppendLine("        switch (invocation.Method)");
        sb.AppendLine("        {");
        foreach (var method in grain.Methods)
        {
            var arg = method.RequestType is null
                ? string.Empty
                : $"invocation.DecodeRequest<{CsType(method.RequestType)}>()";
            sb.AppendLine($"            case \"{method.Name}\":");
            if (method.ReturnType is null)
            {
                sb.AppendLine($"                await grain.{method.Name}({arg});");
                sb.AppendLine("                return invocation.EncodeUnit();");
            }
            else
            {
                sb.AppendLine($"                return invocation.Encode(await grain.{method.Name}({arg}));");
            }
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw BridgeException.UnknownMethod(InterfaceName, invocation.Method);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>The generated class name, e.g. <c>ICounterGrain</c> → <c>CounterGrainInvoker</c>.</summary>
    public static string ClassName(DiscoveredGrain grain)
    {
        var name = grain.Interface.Name;
        if (name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]))
        {
            name = name[1..];
        }

        return name + "Invoker";
    }

    private static string CsType(Type type)
    {
        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            var baseName = (definition.FullName ?? definition.Name);
            var tick = baseName.IndexOf('`', StringComparison.Ordinal);
            if (tick >= 0)
            {
                baseName = baseName[..tick];
            }

            var args = string.Join(", ", type.GetGenericArguments().Select(CsType));
            return $"global::{baseName.Replace('+', '.')}<{args}>";
        }

        return $"global::{(type.FullName ?? type.Name).Replace('+', '.')}";
    }
}
